import { useEffect, useRef, useState, type ReactNode } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import {
  ArrowRight, BookOpen, Check, ChevronDown, Clock3, Download, ExternalLink,
  Mail, MapPin, Menu, MessageCircle, Phone, Play, Quote, Sparkles, X,
} from 'lucide-react'
import './App.css'

type Course = { name: string; level: string; detail: string; tag: string; color: string; mode: string }
const courses: Course[] = [
  { name: 'Foundation', level: 'Grades 8–10', detail: 'Build clear concepts before they become difficult.', tag: 'School excellence', color: 'sage', mode: 'Offline · Hybrid' },
  { name: 'JEE / NEET', level: 'Grades 11–12', detail: "Focused preparation for India's most competitive exams.", tag: 'Exam prep', color: 'gold', mode: 'Offline · Online' },
  { name: 'Board Mastery', level: 'Grades 10–12', detail: 'Structured revision that turns effort into marks.', tag: 'Boards', color: 'coral', mode: 'Offline · Hybrid' },
  { name: 'Crash Courses', level: 'All levels', detail: 'High-impact sprints for the final weeks that count.', tag: 'Short format', color: 'blue', mode: 'Online · Weekend' },
]
const navItems = [['Courses', '/courses'], ['Faculty', '/faculty'], ['Results', '/results'], ['Fees', '/fees'], ['Study material', '/study-material'], ['About', '/about']]

function Brand() { return <Link className="brand" to="/" aria-label="Quantum Classes home"><span className="brand-mark"><span>Q</span><i /></span><span><strong>QUANTUM</strong><small>CLASSES</small></span></Link> }
function Header() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  useEffect(() => setOpen(false), [location.pathname])
  return <>
    <div className="announcement"><span>Admissions open for 2026–27</span><Link to="/enquiry">Book a free counselling call <ArrowRight size={14} /></Link></div>
    <header className="site-header">
      <Brand /><button className="menu-toggle" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
      <nav className={open ? 'main-nav open' : 'main-nav'} aria-label="Main navigation">
        {navItems.map(([label, path]) => <NavLink key={path} to={path} className={({ isActive }) => isActive ? 'active' : ''}>{label}</NavLink>)}
        <Link className="nav-cta" to="/enquiry">Enquire now <ArrowRight size={15} /></Link>
      </nav>
    </header>
  </>
}
function Footer() { return <footer><div className="footer-top"><Brand /><p>Clear thinking.<br />Confident futures.</p><div className="footer-links"><div><strong>Explore</strong><Link to="/courses">Courses</Link><Link to="/faculty">Faculty</Link><Link to="/results">Results</Link><Link to="/fees">Fees</Link></div><div><strong>Visit</strong><span>Sector 18, Noida</span><span>Mon–Sat · 8am–8pm</span><a href="mailto:hello@quantumclasses.in">hello@quantumclasses.in</a></div></div><div className="socials"><strong>Follow along</strong><div><a href="#instagram" aria-label="Instagram"><MessageCircle size={18} /></a><a href="#linkedin" aria-label="LinkedIn"><BookOpen size={18} /></a><a href="#youtube" aria-label="YouTube"><Play size={18} /></a></div></div></div><div className="footer-bottom"><span>© 2026 Quantum Classes. All rights reserved.</span><span>Made for curious minds.</span></div></footer> }
function WhatsApp() { return <a className="whatsapp" href="https://wa.me/919876543210?text=Hi%2C%20I%27d%20like%20to%20know%20more%20about%20Quantum%20Classes%20courses." target="_blank" rel="noreferrer" aria-label="Chat with Quantum Classes on WhatsApp"><MessageCircle size={23} /></a> }
function Meta({ title, description }: { title: string; description: string }) { useEffect(() => { document.title = `${title} | Quantum Classes`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta) }; meta.setAttribute('content', description) }, [title, description]); return null }
function PageHero({ eyebrow, title, description }: { eyebrow: string; title: ReactNode; description: string }) { return <section className="page-hero"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><strong>{eyebrow}</strong></div><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{description}</p></section> }
function EnquiryCTA() { return <section className="compact-cta"><div><span className="kicker light">Your next step</span><h2>Find the right<br /><em>place to begin.</em></h2></div><p>Tell us where you are headed. Our counsellor will help you find a clear, practical path.</p><Link className="button button-light" to="/enquiry">Book a free counselling call <ArrowRight size={16} /></Link></section> }
function Layout({ children }: { children: ReactNode }) { return <div className="site-shell"><Header /><main>{children}</main><Footer /><WhatsApp /></div> }
function Stats({ compact = false }: { compact?: boolean }) { const ref = useRef<HTMLElement>(null); const [visible, setVisible] = useState(false); useEffect(() => { const observer = new IntersectionObserver(([entry]) => setVisible(entry.isIntersecting), { threshold: .25 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect() }, []); return <section className={compact ? 'stats-strip compact' : 'stats-strip'} ref={ref} aria-label="Quantum Classes statistics">{[['5,000+', 'students taught'], ['800+', 'top exam selections'], ['15+', 'years of excellence'], ['40%', 'average improvement']].map(([n, label], i) => <div className="stat" key={label}><strong>{visible ? n : '0'}</strong><span>{label}</span><i>{i < 3 ? '↗' : '↑'}</i></div>)}</section> }
function CourseCard({ course, detailed = false, index = 0 }: { course: Course; detailed?: boolean; index?: number }) { return <article className={`course-card ${course.color} ${detailed ? 'detailed' : ''}`}><div className="course-top"><span>0{index + 1}</span><span className="course-tag">{course.tag}</span></div><div><h3>{course.name}</h3><p>{course.detail}</p></div><div className="course-meta"><span><BookOpen size={15} /> {course.level}</span><span><Clock3 size={15} /> {detailed ? course.mode : '12–24 months'}</span></div>{detailed && <div className="course-syllabus"><strong>Includes</strong><span>Concept classes · Study material · Weekly tests</span></div>}<Link to="/enquiry">{detailed ? 'Enquire about this batch' : 'View programme'} <ArrowRight size={16} /></Link></article> }
function EnquiryForm() { const [submitted, setSubmitted] = useState(false); if (submitted) return <div className="success-state"><span><Check size={24} /></span><h3>We have got your note.</h3><p>Thanks for reaching out. Our counsellor will call you within 24 hours.</p><button className="under-link" onClick={() => setSubmitted(false)}>Send another enquiry <ArrowRight size={15} /></button></div>; return <form onSubmit={(e) => { e.preventDefault(); setSubmitted(true) }}><div className="form-heading"><span>Free counselling call</span><strong>Find your fit</strong></div><div className="form-grid"><label>Name<input required placeholder="Your name" /></label><label>Phone number<input required type="tel" placeholder="+91 98765 43210" /></label><label>Class / grade<select defaultValue="" required><option value="" disabled>Select class</option><option>Class 8–10</option><option>Class 11–12</option><option>College</option></select><ChevronDown size={15} /></label><label>Interested in<select defaultValue="" required><option value="" disabled>Select programme</option><option>Foundation</option><option>JEE / NEET</option><option>Board Mastery</option></select><ChevronDown size={15} /></label></div><label>Anything we should know? <textarea placeholder="Tell us about your goals (optional)" rows={3} /></label><label className="consent"><input type="checkbox" required /> <span>I agree to be contacted by Quantum Classes via phone or WhatsApp.</span></label><button className="button button-primary form-submit" type="submit">Request a callback <ArrowRight size={17} /></button></form> }

function Home() { return <><Meta title="Home" description="Quantum Classes helps students build clear concepts, confidence and strong exam results." /><section className="hero-section"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Trusted by 5,000+ families since 2010</div><h1>Learning that<br /><em>moves you forward.</em></h1><p className="hero-lede">A focused, thoughtful approach to school and competitive exam preparation. Where strong fundamentals become confident futures.</p><div className="hero-actions"><Link className="button button-primary" to="/enquiry">Book a free demo <ArrowRight size={17} /></Link><Link className="button button-text" to="/courses"><span className="play-icon"><Play size={12} fill="currentColor" /></span> Explore programmes</Link></div><div className="hero-proof"><div className="avatars"><span>AK</span><span>SR</span><span>PM</span><span>+</span></div><p><strong>92% of students</strong><br />improve by 2+ grades</p></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=85" alt="Students studying together in a bright classroom" /><div className="image-wash" /></div><div className="hero-note"><span className="note-icon"><Sparkles size={16} /></span><span><b>Small batches.</b><br />Real attention.</span></div><div className="hero-stamp"><strong>15</strong><span>years of<br />excellence</span></div></div></section><Stats /><section className="section teaser-grid"><div className="section-intro"><div><span className="kicker">A clear path forward</span><h2>Everything you need<br /><em>to keep moving.</em></h2></div><p>Explore the people, programmes and proof behind the Quantum approach.</p></div><div className="teaser-cards"><Link className="teaser-card" to="/courses"><span>01</span><h3>Programmes built around your goals.</h3><ArrowRight /></Link><Link className="teaser-card" to="/faculty"><span>02</span><h3>Teachers who stay curious.</h3><ArrowRight /></Link><Link className="teaser-card" to="/results"><span>03</span><h3>Quietly remarkable results.</h3><ArrowRight /></Link><Link className="teaser-card" to="/fees"><span>04</span><h3>Clear fees, no surprises.</h3><ArrowRight /></Link></div></section><EnquiryCTA /></> }
function Courses() { const [filter, setFilter] = useState('All programmes'); const filtered = filter === 'All programmes' ? courses : courses.filter((c) => c.tag === filter); return <><Meta title="Courses & Batches" description="Explore Foundation, JEE, NEET, Board and Crash Course programmes at Quantum Classes." /><PageHero eyebrow="Courses & batches" title={<>Programmes built<br /><em>around your goals.</em></>} description="Structured learning paths for school excellence, board confidence and competitive exam preparation." /><Link className="sticky-enquire" to="/enquiry">Enquire now <ArrowRight size={15} /></Link><section className="section courses-page"><div className="filter-row" role="tablist">{['All programmes', 'School excellence', 'Exam prep', 'Boards'].map((item) => <button key={item} className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="course-grid">{filtered.map((course, i) => <CourseCard course={course} detailed key={course.name} index={i} />)}</div></section><EnquiryCTA /></> }
function Faculty() { const faculty = [['Dr. Meera Sharma', 'Physics · M.Sc., IIT Delhi', '18 years · Makes difficult ideas feel obvious', 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=500&q=85'], ['Rohan Malhotra', 'Mathematics · M.Tech., NIT', '12 years · Builds calm exam confidence', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=85'], ['Ananya Iyer', 'Biology · M.Sc., AIIMS', '10 years · Connects every concept to life', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=85'], ['Kabir Singh', 'Chemistry · M.Sc., DU', '9 years · Turns practice into instinct', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85']]; return <><Meta title="Faculty" description="Meet the experienced, thoughtful faculty behind Quantum Classes." /><PageHero eyebrow="Faculty" title={<>Teachers who<br /><em>stay curious.</em></>} description="Deep subject knowledge, clear explanations and genuine attention for every learner." /><section className="section faculty-page"><div className="faculty-grid">{faculty.map(([name, subject, bio, photo], i) => <article className="faculty-card" key={name}><img src={photo} alt={`${name}, ${subject}`} /><span>0{i + 1}</span><div><h3>{name}</h3><p>{subject}</p><small>{bio}</small></div></article>)}</div></section><EnquiryCTA /></> }
function Results() { const [year, setYear] = useState('2025'); return <><Meta title="Results" description="See Quantum Classes student results, selections and academic improvement." /><PageHero eyebrow="Results" title={<>Quietly remarkable<br /><em>results.</em></>} description="Every number here represents a student who found their next level." /><Stats compact /><section className="section results-page"><div className="year-tabs light-tabs">{['2024', '2025', '2026'].map((item) => <button className={year === item ? 'active' : ''} onClick={() => setYear(item)} key={item}>{item}</button>)}</div><div className="result-grid"><article className="result-card featured"><div className="result-photo"><img src="https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=700&q=85" alt="Arjun Mehta celebrating his JEE result" /><span>JEE Main</span></div><div className="result-info"><strong>98.7<span> percentile</span></strong><h3>Arjun Mehta</h3><p>JEE Advanced {year} · Rank 4,821</p></div></article><article className="result-card result-light"><div className="result-score"><span>NEET</span><strong>674<small>/ 720</small></strong><p>Ananya Rao · {year}</p></div><div className="quote-mark"><Quote size={20} /></div></article><article className="result-card result-light"><div className="result-score gold-score"><span>CBSE XII</span><strong>96.4<small>%</small></strong><p>Rhea Kapoor · {year}</p></div><div className="quote-mark"><Quote size={20} /></div></article></div></section><EnquiryCTA /></> }
function Fees() { return <><Meta title="Fee Structure" description="Compare Quantum Classes fees, durations, inclusions and installment options." /><PageHero eyebrow="Fee structure" title={<>Investment in<br /><em>what comes next.</em></>} description="No surprise costs. Flexible payment plans. Every programme includes study material, tests and mentor support." /><section className="section fee-page"><div className="fee-table-wrap"><table><thead><tr><th>Programme</th><th>Duration</th><th>Fee from</th><th>Includes</th><th></th></tr></thead><tbody>{[['Foundation', '12 months', '₹42,000', 'Classes · Tests · Mentoring'], ['JEE / NEET', '24 months', '₹1,28,000', 'Classes · Material · Test series'], ['Board Mastery', '10 months', '₹36,000', 'Classes · Revision · Doubt desk'], ['Crash Courses', '8–12 weeks', '₹18,000', 'Revision · Practice · Doubt desk']].map((row) => <tr key={row[0]}>{row.map((cell, i) => <td key={cell} className={i === 0 ? 'fee-name' : ''}>{cell}</td>)}<td><Link to="/enquiry" aria-label={`Enquire about ${row[0]}`}><ArrowRight size={17} /></Link></td></tr>)}</tbody></table></div><div className="fee-foot"><span><Check size={16} /> Scholarships available for eligible students</span><Link className="under-link" to="/enquiry">Talk to us about installment plans <ArrowRight size={15} /></Link></div><div className="info-panels"><div><strong>Installment plans</strong><p>Monthly and term-based options are available for all full-year programmes.</p></div><div><strong>Scholarships</strong><p>Ask our counsellor about merit and need-based fee support.</p></div></div></section><EnquiryCTA /></> }
function StudyMaterial() { const resources: [string, string, string, boolean][] = [['Physics', 'Class 12 · Formula sheet', 'PDF · 2.4 MB', false], ['Mathematics', 'JEE · Practice set 04', 'PDF · 4.1 MB', true], ['Biology', 'NEET · Human physiology', 'PDF · 1.8 MB', false], ['Chemistry', 'Organic reactions quick guide', 'PDF · 3.2 MB', true]]; return <><Meta title="Study Material" description="Browse Quantum Classes notes, practice sets and exam guides." /><PageHero eyebrow="Study material" title={<>Good preparation<br /><em>needs good tools.</em></>} description="Selected notes, practice sets and exam guides from our faculty, organised for focused practice." /><section className="section material-page"><div className="filter-row"><button className="filter active">All subjects</button><button className="filter">Class 10</button><button className="filter">Class 12</button><button className="filter">JEE / NEET</button></div><div className="resource-library">{resources.map(([subject, title, size, gated]) => <div className="resource-row" key={title}><span className="resource-icon"><Download size={17} /></span><span><small>{subject}</small><strong>{title}</strong><em>{size}</em></span>{gated ? <small className="login-note">Login required</small> : <Link to="/enquiry" aria-label={`Download ${title}`}><ExternalLink size={16} /></Link>}</div>)}</div></section><EnquiryCTA /></> }
function About() { return <><Meta title="About" description="Learn about Quantum Classes, our story, teaching method and learning spaces." /><PageHero eyebrow="About Quantum" title={<>A place to feel<br /><em>capable.</em></>} description="Education should make you more curious, not just more prepared." /><section className="section about-page"><div className="about-copy"><span className="kicker">Our story</span><h2>Started small.<br /><em>Still personal.</em></h2><p>Quantum began with one teacher, twelve students and a belief that the right kind of attention can change a learner’s relationship with a subject.</p><p>Today, our rooms are fuller, but the belief has stayed the same. Small batches, honest feedback and teachers who remain interested in how each student thinks.</p><div className="mission-grid"><div><strong>Mission</strong><p>Make difficult learning feel possible through clarity and care.</p></div><div><strong>Vision</strong><p>Build independent, curious learners for the long term.</p></div></div></div><div className="about-image"><img src="https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=85" alt="Students learning together in a Quantum Classes classroom" /><div className="about-note"><span>Since</span><strong>2010</strong><span>New Delhi · Noida</span></div></div></section><section className="section infrastructure"><span className="kicker">Built for attention</span><h2>Spaces that support<br /><em>good study habits.</em></h2><div className="infra-grid"><div><strong>01</strong><h3>Digital classrooms</h3><p>Clear visuals and recorded revision for difficult topics.</p></div><div><strong>02</strong><h3>Quiet library</h3><p>A focused place to revise, practise and ask better questions.</p></div><div><strong>03</strong><h3>Science labs</h3><p>Hands-on learning that gives abstract concepts a physical shape.</p></div></div></section><EnquiryCTA /></> }
function Contact() { return <><Meta title="Contact" description="Visit, call or message Quantum Classes in Sector 18, Noida." /><PageHero eyebrow="Contact" title={<>Come say<br /><em>hello.</em></>} description="Questions about batches, fees or the right starting point? We are here to help." /><section className="section contact-page"><div className="contact-details"><div><MapPin /><span><strong>Visit us</strong>Sector 18, Noida, Uttar Pradesh<br />Mon–Sat · 8am–8pm</span></div><div><Phone /><span><strong>Call us</strong>+91 98765 43210<br />+91 98765 43211</span></div><div><Mail /><span><strong>Email us</strong>hello@quantumclasses.in</span></div></div><div className="map-placeholder"><MapPin size={27} /><strong>Quantum Classes · Sector 18</strong><span>Interactive map available on request</span></div></section><EnquiryCTA /></> }
function Enquiry() { return <><Meta title="Enquiry" description="Book a free counselling call with Quantum Classes." /><PageHero eyebrow="Enquiry" title={<>Let’s make a<br /><em>plan together.</em></>} description="Tell us a little about where you are. A counsellor will call within 24 hours to help you find the right fit." /><section className="enquiry-page"><div className="enquire-copy"><span className="kicker light">Free counselling call</span><h2>Find your<br /><em>fit.</em></h2><p>We will help you compare programmes, batch timings and the best next step for your goals.</p><div className="contact-line"><Phone size={17} /><span><strong>Prefer to talk?</strong><br />+91 98765 43210</span></div></div><div className="form-card"><EnquiryForm /></div></section></> }
function App() { return <BrowserRouter><Layout><Routes><Route path="/" element={<Home />} /><Route path="/courses" element={<Courses />} /><Route path="/faculty" element={<Faculty />} /><Route path="/results" element={<Results />} /><Route path="/fees" element={<Fees />} /><Route path="/study-material" element={<StudyMaterial />} /><Route path="/about" element={<About />} /><Route path="/contact" element={<Contact />} /><Route path="/enquiry" element={<Enquiry />} /></Routes></Layout></BrowserRouter> }
export default App
